# Generated by Django 5.0.7 on 2024-09-06 19:30

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_register',
            name='verification_code',
            field=models.CharField(default=users.models.generate_verification_code, max_length=6),
        ),
    ]
