# Generated by Django 5.0.7 on 2024-09-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioyvideo', '0002_audioyvideo_state'),
        ('carrito', '0001_initial'),
        ('componentes', '0002_componentes_state'),
        ('equipos', '0002_equipos_state'),
        ('redes', '0002_redes_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='audioyvideo',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='componentes',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='equipos',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='redes',
        ),
        migrations.AddField(
            model_name='carrito',
            name='audioyvideo',
            field=models.ManyToManyField(blank=True, to='audioyvideo.audioyvideo'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='componentes',
            field=models.ManyToManyField(blank=True, to='componentes.componentes'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='equipos',
            field=models.ManyToManyField(blank=True, to='equipos.equipos'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='redes',
            field=models.ManyToManyField(blank=True, to='redes.redes'),
        ),
    ]
