# Generated by Django 5.0.7 on 2024-09-12 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioyvideo', '0002_audioyvideo_state'),
        ('carrito', '0002_remove_carrito_audioyvideo_and_more'),
        ('componentes', '0002_componentes_state'),
        ('equipos', '0002_equipos_state'),
        ('redes', '0002_redes_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='audioyvideo',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='componentes',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='equipos',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='redes',
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrito.carrito')),
                ('producto_audioyvideo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audioyvideo.audioyvideo')),
                ('producto_componentes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentes.componentes')),
                ('producto_equipos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.equipos')),
                ('producto_redes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redes.redes')),
            ],
        ),
    ]
