# Generated by Django 5.0.7 on 2024-09-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_remove_carrito_audioyvideo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_name', models.CharField(max_length=50)),
                ('producto_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producto_quantity', models.IntegerField(default=0)),
                ('producto_state', models.BooleanField(default=False)),
            ],
        ),
    ]
