# Generated by Django 5.0.7 on 2024-09-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_remove_vendidos_recibo_code_recibo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='recibo_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
