# Generated by Django 5.0.7 on 2024-09-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_alter_recibo_recibo_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='recibo_code',
            new_name='recibo_codigo',
        ),
    ]
