# Generated by Django 5.0.7 on 2024-09-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0008_rename_recibo_code_recibo_recibo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='recibo_codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
