# Generated by Django 5.0.7 on 2024-09-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0009_alter_recibo_recibo_codigo'),
    ]

    operations = [
    ]
