# Generated by Django 5.0.7 on 2024-09-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0010_fill_unique_recibo_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendidos',
            name='producto_compra',
            field=models.BooleanField(default=False),
        ),
    ]
