# Generated by Django 5.0.7 on 2024-09-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0011_vendidos_producto_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendidos',
            name='producto_codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
