# Generated by Django 5.0.7 on 2024-09-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0012_vendidos_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendidos',
            name='producto_codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
