# Generated by Django 5.0.7 on 2024-09-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0013_alter_vendidos_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='recibo_codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
