# Generated by Django 5.0.7 on 2024-09-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0014_alter_recibo_recibo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='recibo_codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
