# Generated by Django 5.0.7 on 2024-09-15 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0015_alter_recibo_recibo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito'),
        ),
    ]
