# Generated by Django 5.0.7 on 2024-09-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0002_componentes_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentes',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
