# Generated by Django 5.0.7 on 2024-09-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_equipos_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='details',
            field=models.CharField(max_length=500),
        ),
    ]
